@startuml

actor User
title Diagrama Secuencia TP2 - Jugador contesta una pregunta con augmenter
hide footbox

participant ": Game" as game
participant "player : Player" as player
participant ": Question" as question
participant "matchScore : Score" as score
participant "augmenter : ScoreAugmenter" as augmenter


User -> game:1.nextTurn\n(selectedOptions, augmenter)
activate game
game->>question:1.1.calculatePoints\n(selectedOptions, augmenter)
activate question
question ->> augmenter:isForPenalty()
activate augmenter
augmenter -->> question:false
deactivate augmenter
question ->> score:new Score(augmenter)
activate score
score -->> question:score
deactivate score
question -->>game:reply.score
deactivate question
game->>MatchResult:2.new
activate MatchResult
MatchResult->>player:2.1.getAugmenter
activate player
player-->>MatchResult:reply.augmenter
deactivate player
MatchResult-->>game:reply.matchResults.add\n(matchResult)
deactivate MatchResult

@enduml