@startuml

actor User
title Diagrama Secuencia TP2 - Jugador contesta una pregunta
hide footbox

participant "player : Player" as player
participant "score : Score" as score
participant "noAugmenter : ScoreAugmenter" as noMultiplier

loop n players
User -> player ** : new Player("Jugador1")
player --> User : player
end loop

loop n questions 
loop n options 
User -> option ** : new GameOption(optionText)
option --> User : option
end loop
User -> question ** : new Question(stringText, listaOpciones)
question --> User : question
User -> question : setCorrectOptions()
end loop

User -> game ** : new Game(jugadores, preguntas)
game --> User : game
User -> game : start()
activate game

loop for n players
User -> game : nextTurn(selectedOption)
game-> game : nextTurn(selectedOption, NoMultiplier)
activate game

game -> score** : new Score(points, NoMultiplier)
score --> game : matchScore

game -> matchResult** : new matchResult\n(currentPlr, matchScore)
matchResult --> game : matchResults.add()

game -> ScoreCalculator : calculateRoundEndResults(matchResults)
deactivate game
activate ScoreCalculator
ScoreCalculator -> ScoreCalculator : calculateAugmenters\n(matchResult)
ScoreCalculator -> matchResult : applyScoreAugmenter\n(matchResults)
activate matchResult
matchResult -> noMultiplier : applyScoreAugmenter\n(matchScore, result.getMatchScore()) 
deactivate matchResult
deactivate ScoreCalculator
ScoreCalculator -> ScoreCalculator : sumMatchScore\n(MatchResults)
ScoreCalculator -> matchResult : sumMatchScoreToPlayer\n(matchScore)
activate matchResult
matchResult -> player : sumScore(matchScore)
deactivate matchResult
end loop
deactivate game

@enduml
