@startuml

actor User
title Diagrama Secuencia TP2 - Jugador contesta una pregunta
hide footbox

participant ": Game" as game
participant "player : Player" as player
participant ": Question" as question
participant "matchScore : Score" as score
participant "augmenter : NoMultiplier" as augmenter


User -> game:1.nextTurn\n(selectedOptions)
activate game
game ->> augmenter:new
activate augmenter
augmenter -->> game:augmenter
deactivate augmenter
game-> game:2.nextTurn\n(selectedOptions, augmenter)
activate game
game->>question:2.1.calculatePoints\n(selectedOptions, augmenter)
activate question
question ->> augmenter:applies(hasPenalty())
activate augmenter
augmenter -->> question:this
deactivate augmenter
question ->> score:new Score(augmenter)
activate score
score -->> question:score
deactivate score
question -->>game:reply.score
deactivate question
game->>MatchResult:3.new
activate MatchResult
MatchResult->>player:3.1.getAugmenter
activate player
player-->>MatchResult:reply.augmenter
deactivate player
MatchResult-->>game:reply.matchResults.add\n(matchResult)
deactivate MatchResult
deactivate game
deactivate game
@enduml
