@startuml DiagramaUML-DetalleAugmentation-TP2

skinparam classAttributeIconSize 0

abstract ScoreAugmenter{
    + {abstract}applyScoreAugmenter(Score score, Score opponentScore)
    + {abstract}isForPenalty() : boolean
    + {abstract}getUsesPerPlayer() : int
    + applies(boolean hasPenalty) : ScoreAugmenter
    + equals(Object obj) : boolean
}

class ThreeMultiplyer{
    + applyNewScore(Score score, Score opponentScore)
    + getUsesPerPlayer() : int
    + isForPenalty() : boolean
}

class TwoMultiplyer{
    + applyNewScore(Score score, Score opponentScore)
    + getUsesPerPlayer() : int
    + isForPenalty() : boolean
}

class ExclusivityMultiplier{
    + applyNewScore(Score score, Score opponentScore)
    + getUsesPerPlayer() : int
    + isForPenalty() : boolean
}

class NoMultiplier{
    + applyNewScore(Score score, Score opponentScore)
    + getUsesPerPlayer() : int
    + isForPenalty() : boolean
}


ThreeMultiplyer --left|> ScoreAugmenter
TwoMultiplyer --right|> ScoreAugmenter
NoMultiplier --down|> ScoreAugmenter

ExclusivityMultiplier --up|> ScoreAugmenter

@enduml