@startuml

actor User
title Diagrama Secuencia TP2 - Jugador contesta una pregunta con augmenter
hide footbox

participant "player : Player" as player
participant "score : Score" as score
participant "multiplierX2 : TwoMultiplier" as multiplierx2

loop n players
User -> player ** : new Player("Jugador1")
player --> User : player
end loop

loop n questions 
loop n options 
User -> option ** : new GameOption(optionText)
option --> User : option
end loop
User -> question ** : new Question(stringText, listaOpciones)
question --> User : question
User -> question : setCorrectOptions(opcionesCorrectas)
end loop

User -> game ** : new Game(jugadores, preguntas)
game --> User : game
User -> game : start()
activate game

loop for n players
User -> game : nextTurn(selectedOption, multiplierx2)
activate game

game -> score** : new Score(points, multiplierx2)
score --> game : matchScore

game -> matchResult** : new matchResult\n(currentPlr, matchScore)
matchResult --> game : matchResults.add()

game -> ScoreCalculator : calculateRoundEndResults(matchResults)
deactivate game
activate ScoreCalculator
ScoreCalculator -> ScoreCalculator : calculateAugmenters\n(matchResult)
activate ScoreCalculator
ScoreCalculator -> matchResult : applyScoreAugmenter\n(matchResults)
activate matchResult
matchResult -> multiplierx2 : applyScoreAugmenter\n(matchScore, result.getMatchScore()) 
activate multiplierx2
multiplierx2 -> score : setValue(score.getValue() * 2)
deactivate multiplierx2
deactivate matchResult
deactivate ScoreCalculator
ScoreCalculator -> ScoreCalculator : sumMatchScore\n(MatchResults)
activate ScoreCalculator
ScoreCalculator -> matchResult : sumMatchScoreToPlayer\n(matchScore)
activate matchResult
matchResult -> player : sumScore(matchScore)
deactivate matchResult
deactivate ScoreCalculator
end loop
deactivate ScoreCalculator
deactivate game

@enduml